### ISSUE TITLE
Missing field in `inexact` doc

### ISSUE THREAD

**Issue by Dronte** [nvie/decoders#1017]
**Description of the bug**
Looks like the documentation of `inexact` decoder is missing field for `y`. 
It is now
```
const decoder = inexact({
    x: number,
});
```
While should be
```
const decoder = inexact({
    x: number,
    y: number,
});
```
as in `exact` decoder above. 

Or am I missing something?

**Comment by nvie** [comment]
You’re right! Thanks for pointing it out. I’ll get this fixed.
