### ISSUE TITLE
Support for Enums

### ISSUE THREAD

**Issue by LcTwisk** [nvie/decoders#209]
Let's say there is an enum like this:

```
enum Alphabet {
  a = "a",
  b = "b"
}
```
A possible decoder would be:

`const decoder = either2(hardcoded("a"), hardcoded("b"))`

This doesn't work for enums with more than 9 cases atm. What do you think of introducing another method that checks input agains an array of values with the same type?

Something like `oneOf(values: [T])`

**Comment by LcTwisk** [comment]
Ahh I see!
Didn't think about nesting the either methods, this will work for my use case I guess 👍 

For TS enums it would still be useful to add something like:
```
export function enum_(members: Array<string | number>): Decoder<string | number> {
    return (blob: mixed) => (members.includes(mixed) ? Ok(blob) : Err(annotate(blob, `Must be one of ${members.join(', ')}`)));
}

```

PS: Yep, I meant `constant` indeed, will change it :)

**Comment by nvie** [comment]
> For TS enums it would still be useful to add something like

I agree that this would be a nice generic decoder to add to the library, as a convenience for enforcing a string (or number) value is one of a few preset alternatives.  It's good to note however that the output of such a decoder will always be a `string` at best, not a union of specific string constants.

If you have something like:

```javascript
enum MyEnum {
  foo = "foo",
  bar = "bar",
}

const value = guard(oneOf(['foo', 'bar']))(request.body);
```

Then to the type system `value` will just be a `string` (even though at runtime this can only ever be `'foo'` or `'bar'`), but the type system doesn't know.

If you have a function that takes an Enum:

```javascript
function doSomething(thing: MyEnum) { ... }

doSomething(value)
//          ^^^^^ Error: string is incompatible with MyEnum
```

To solve this, you will still have to use `either(constant('foo'), constant('bar'))`.

That said, if you want to use `oneOf()` as an alternative for something like `regex()` (check specific string values at runtime but return a string type), then yes I agree it's still a nice/useful addition.

@LcTwisk Ideas?

**Comment by lusarz** [comment]
Hi there, any update on this?

**Comment by lusarz** [comment]
It works! Thank you @nvie

**Comment by nvie** [comment]
In the latest [v2.3.0](https://github.com/nvie/decoders/releases/tag/v2.3.0), `enum_` is now fully supported (see [docs](https://decoders.cc/api.html#enum_)).
