### ISSUE TITLE
TypeScript optional keys for DecoderType inference

### ISSUE THREAD

**Issue by camargo** [nvie/decoders#292]
If we create a `Decoder` called `dFoo`:

```ts
import * as d from 'decoders';
```

```ts
const dFoo = d.object({
  id: d.string,
  name: d.optional(d.string)
});
```

Then infer the type from it via:

```ts
type Foo = d.$DecoderType<typeof dFoo>;
```

The inferred type is:

```ts
type Foo = {
   id: string;
   name: string | undefined;
}
```

That means when we use `Foo` we need to set a `name` key equal to `undefined`, instead of just omitting it:

```ts
const someFoo: Foo = {
  id: '42',
  name: undefined
};
```

Is it possible to have the inferred type use `?` so we can just omit the optional key:

```ts
type Foo = {
    id: string;
    name?: string;
}
```

Thanks

**Comment by nvie** [comment]
Hmm... Sounds like a behavioral difference between TypeScript and Flow. In Flow, what you desire seems to be the case already... Not super sure how to express this in TypeScript yet. Would have to look a bit deeper into what would be possible in this definition: https://github.com/nvie/decoders/blob/master/src/types/object.d.ts#L5

If you have ideas, please let me know. Happy to adjust!

**Comment by nvie** [comment]
After some hours of playing around with various alternatives today, I think I found a nice solution for this that would be similar to this trick, but will not lead to the messy inferred types. You can find my alternative implementation in #515 .
