### ISSUE TITLE
Typing for optional key does not allow for missing key 

### ISSUE THREAD

**Issue by ottokruse** [nvie/decoders#439]
Hi, can you help me fix the below?
THANKS

This:

```
object({
  name: string,
  address: optional(string),
})
```

Should decode to type:

```
{
  name: string;
  address?: string;
}
```

But actually decodes to type:

```
{
  name: string;
  address: string | undefined;
}
```

Which according to my TypeScript (3.7.5) makes address a mandatory key that may have value undefined.

I extract the type like this, maybe not right?

```
export const propGuard = guard(
  object({
    name: string,
    address: optional(string),
  })
);
export type MyProps = ReturnType<typeof propGuard>;

// This doesn't compile:
const props: MyProps = {
  name: '123',
}
```

Runtime is fine and does allow for missing key.

**Comment by ottokruse** [comment]
I run into this in unit tests, where I supply a JS object directly, instead of letting the decoder parse JSON

**Comment by lydell** [comment]
This sounds like #292. There’s a PR that potentially solves the issue: #376

**Comment by ottokruse** [comment]
Still relevant issue to me

FYI I use decoders a lot while coding with AWS CDK, as a means to have a schema for config files, and typings for my Stack props

**Comment by nvie** [comment]
After some hours of playing around with various alternatives today, I think I found a nice solution for this that would be similar to this trick, but will not lead to the messy inferred types.  You can find my alternative implementation in #515 .
