### ISSUE TITLE
Is there a way to combine decoders?

### ISSUE THREAD

**Issue by xAKLx** [nvie/decoders#578]
For example:

- If I have 2 decoders that share a lot of values
- If I have a type like this:
```typescript
export interface AnObject extends Record<string, string> {
  id: number;
  name: string;
}
```
I would need to find a way to combine
```typescript
object({id: number, name: string})
//And
dict(string)
```

**Comment by nvie** [comment]
Hmm, interesting. Is this a valid TypeScript type? Does this behave differently than `{ id: number, name: string } & Record<string, string>`? Because the `id` would have to be both a number and a string? Is this possible?

Or is this more similar to `{ id: number, name: string, [key: string]: string }`?

**Comment by xAKLx** [comment]
Now that I checked again it is not a valid type. My actual original scenario was:
```typescript
export interface AnObject extends Record<string, unknown> {
  id: number;
  name: string;
}
```
It looks like using `inexact` works fine for this case. Merging decoders could be useful for the following (and for when we have decoders with shared properties):
```typescript
interface X extends Record<string, string | number> {
  id: number;
}
```
This one is valid and results in locking id to number while the other values are either number or string.

**Comment by nvie** [comment]
This might be possible if we'd introduce a second optional argument to `inexact()` which would allow you to specify a decoder for the "rest fields", e.g.

```typescript
// Decoder<{ id: number, [key: string]: string | number }>
inexact(
  { id: number },
  either(string, number),
)
```

The default value for that optional second argument would be the `unknown` decoder, which matches its current behavior.
