### ISSUE TITLE
Is the documentation for dispatch incorrect?

### ISSUE THREAD

**Issue by ben-eb** [nvie/decoders#592]
Hello 👋 

I'd like to check if the documentation for `dispatch` is correct because I'm running into a problem with it at the moment!

```ts
import {object, string, constant, dispatch, guard } from 'decoders'

type SandboxEnviroment = {
  status: "sandbox";
  name: string;
}

type LiveEnvironment = {
  status: "live";
  name: string;
}

type Environment = SandboxEnviroment | LiveEnvironment

const decodeSandbox = object({
  name: string,
  status: constant('sandbox')
})

const decodeLive = object({
  name: string,
  status: constant('live')
})

const decoder = dispatch('status', {
  live: decodeLive,
  sandbox: decodeSandbox
})

const run = (): Environment =>
  guard(decoder)({
    status: 'live',
    name: 'my-app'
  })
```

The error I get (in `run`) is the following:

```
TS2322: Type '$Values<{ live: { status: string; name: string; }; sandbox: { status: string; name: string; }; }>' is not assignable to type 'Environment'.
Type '{ status: string; name: string; }' is not assignable to type 'Environment'.
Type '{ status: string; name: string; }' is not assignable to type 'LiveEnvironment'.
Types of property 'status' are incompatible.
Type 'string' is not assignable to type '"live"'
```

However the [documentation for `dispatch`](https://github.com/nvie/decoders#dispatch) indicates that the inner type of the decoder will be a union! Is this a bug or an error in the documentation?

Of course, I can leave off the annotations in my `run` function to get this compiling so it's not a blocker. Thought I'd give you a heads up about it though! 🙂

**Comment by nvie** [comment]
Thanks for the report. I think the sublety lies in the definition of the constants. When using `constant('x')` in TypeScript, you should almost always use `constant('x' as 'x')` instead. Otherwise, the inferred type for it will be `string`, not `'x'`. Can you try updating your definitions to:

```typescript
const decodeSandbox = object({
  name: string,
  status: constant('sandbox' as 'sandbox')
})

const decodeLive = object({
  name: string,
  status: constant('live' as 'live')
})
```

Does that do the trick? I'll update the docs for `constant()`.

**Comment by nvie** [comment]
Updated the docs! https://github.com/nvie/decoders#constant

**Comment by ben-eb** [comment]
@nvie Thanks! That did the trick 👍
