### ISSUE TITLE
Is there a way to decode a field in source object into another field in target object

### ISSUE THREAD

**Issue by vjrasane** [nvie/decoders#607]
Having used Elm decoders, decoding a particular field or a combination of them into another field is a common use case for me.

An example could look something like this:

`const decoder:  Decoder<T> = object({ 
   targetField: compose(field('sourceField'), string)
})`

So essentially it would be a 'mixed' decoder that takes its value from another field than its target field.

Is there currently a way to do this? If not, would this be possible to implement?

**Comment by nvie** [comment]
There is no direct way of doing this without cluttering up the API and using the `field()` construct in many other places.

A way that is currently possible is to decode the “original” fields from the source object first, and then “map” the successfully decoded result by a transformer function to the intended output structure. For example:

```js
type Output = {
  a: string,
  b: number,
}

const decoder: Decoder<Output> = map(
  object({
    a: string,
    c: number,
  }),
  obj => ({ ...obj, b: obj.c }),
);
```

**Comment by nvie** [comment]
The API you suggested is something I thought about, but it would require special knowledge about the `field` decoder inside the `object` decoder (so it has implications for composability). It also has implications for annotating error messages inline, which would then need special treatment. I don’t think it’s impossible, but it would definitely be harder to implement. That’s why I haven’t found a better solution for this yet.
