### ISSUE TITLE
How to handle differences between property names

### ISSUE THREAD

**Issue by FactorMouk** [nvie/decoders#624]
Here's my problem. The data comes from the backend with the compound names of the properties with underline, but in the frontend I want them to be camelCase.

How the data comes from backend:
`
{
  id: 'some string',
  status: 'some string',
  token: 'some string',
  due_date: 'some string',
  bank_slip_url: 'some string',
  invoice_url: 'some string',
  created: 'some string'
}
`

Here's my frontend implementation:
`
export class LicensePaymentModel {
  id?: string;
  status?: PaymentStatusEnum;
  token?: string;
  dueDate?: Date;
  bankSlipUrl?: string;
  invoiceUrl?: string;
  created?: Date;
};
`

`
export const licenseDecoder: Decoder<LicensePaymentModel> = object({
  id: string,
  status: string,
  token: string,
  due_date: date,
  bank_slip_url: string,
  invoice_url: string,
  created: date
});
`

I realized that since I'm using Decoder <LicensePaymentModel> in my decoder, the object must have the properties in camelCase, as in my LicensePaymentModel model. I was wondering if there is any way for me to associate the properties that comes from JSON underline with the model's camelCase.

**Comment by nvie** [comment]
There is no direct API for doing that in the current version of decoders. It has been on my mind to add support for this, but I haven't found an API for it that I'm happy with. For now, you could use a library to convert the raw incoming data to camelCase before feeding it to the decoder. Look for libraries like [lodash-humps](https://github.com/cape-io/lodash-humps) , or [camelcase-keys](https://www.npmjs.com/package/camelcase-keys), or something similar.
