### ISSUE TITLE
nonEmptyString not exported in npm package

### ISSUE THREAD

**Issue by shedrachokonofua** [nvie/decoders#630]
I see the export in the code on the repo but not in the package I pulled from npm. I believe all that's needed is a new release.

**Comment by nvie** [comment]
D'oh! You're right. I had fixed that and prepared a release for this already… just didn't push it out yet! It's now published in [v1.23.4](https://github.com/nvie/decoders/releases/tag/v1.23.4). Thanks for pinging me about this here!
