### ISSUE TITLE
Decoder for object with specified key 

### ISSUE THREAD

**Issue by pvarga-dni** [nvie/decoders#638]
Can I create a `Decoder` such as this one

```ts
const withKey = <K extends string, T>(k: K, d: Decoder<T>) => object({[k]: d})
```

so that the resulting type is exact? For example `Decoder<{a: number}>` for `withKey("a", number)`?

Currently this results in something like `Decoder<{[x: string]: number}>` (simplified).

---
Perhaps related, is it possible to take a `Decoder<{...}>` and "merge" a property into it / "extend" it?

`zod` equivalent: https://github.com/colinhacks/zod#extending-objects

**Comment by nvie** [comment]
I got it working if I define it like this:

```ts
const withKey = <K extends string, T>(
  k: K,
  decoder: Decoder<T>
): Decoder<{ [F in K]: T }> =>
  // @ts-ignore-error
  object({ [k]: decoder });
```

Not sure why the object definition and the return type for this decoder aren't compatible, honestly. Hence the `@ts-ignore-error`, which is a little bugger. Hopefully this gets you a step further!

**Comment by pvarga-dni** [comment]
Thank you, indeed that helps!

As this is part of the issue is resolved is it ok if I morph this into a request for the "extend" feature?
