### ISSUE TITLE
Required types

### ISSUE THREAD

**Issue by OliverRadini** [nvie/decoders#648]
Firstly, apologies if this isn't an actual issue and is instead related to my naivety as to how to properly use the library.

Secondly, this is a great library.

My issue is relating to determining that a type is required, and not ever undefined, as far as the Typescript compiler is concerned.

If I have some code:
```js
const testDecoder = object({ success: boolean });
```

TS determines the type to be:
```ts
Decoder<{
    success?: boolean;
}, unknown>
```

My question is, how can I have typescript infer that the key `success` is not optional?

**Comment by nvie** [comment]
Hey, thanks for the bug report! This is weird and should not happen. I remember there was a similar bug report like this, see https://github.com/nvie/decoders/issues/588. I was not able to replicate it, see the steps I laid out there. Can you try that example and see if that still happens for you?

**Comment by OliverRadini** [comment]
Thanks for getting back to me; the example in that issue works fine for me, which is great, I'll have a look at the code I have and attempt to see what the difference is, thanks!

**Comment by OliverRadini** [comment]
For the record, if I put the same type, which is:
```ts
const productsMapShape = object({
  urlset: array(object({ loc: string })),
});
```
The types are fine in the example I've setup from the issue you mentioned, but not in my code. I tried updating my versions to mtach, but no luck, so who knows what's going on.

**Comment by dam5s** [comment]
I just had the same issue and fixed it by setting `strict: true` option in my typescript configuration.

**Comment by dam5s** [comment]
FYI my config was the default generated by `webpack init`. Not sure what justifies having `strict: true` not be the default...
