### ISSUE TITLE
Decoder with constants is throwing an exception. TypeError: (0 , _Result.Ok) is not a function

### ISSUE THREAD

**Issue by Jaywaa** [nvie/decoders#700]
When trying to decode a string to one of 3 constants, am receiving an error `TypeError: (0 , _Result.Ok) is not a function`

[Codepen example](https://codepen.io/jaywaa/pen/YzZMEoy?editors=0011) (open browser console to see error).

Snippet:
```ts
import { guard, either3, constant, Decoder } from "decoders";

const statusDecoder: Decoder<'complete' | 'closed' | 'failed'>
      = either3(constant<'complete'>('complete'), constant<'closed'>('closed'), constant<'failed'>('failed'));

const statusString = 'closed';

const status = guard(statusDecoder)(statusString);

console.log('Decoded:', status);
```

**Comment by nvie** [comment]
That's weird. I cannot replicate this behavior myself in any way locally. If I put the contents you reported in a `foo.ts` file, and run `tsc foo.ts` it all just works. It looks like skypack.dev is doing some code transformations that break this. Have you run into this issue without using skypack.dev?

**Comment by Jaywaa** [comment]
I'm running into the issue locally using npm + Snowpack. I've tried deleting `node_modules` and reinstalling to no avail. I can try using a different bundler and seeing what happens.

**Comment by nvie** [comment]
Interesting. Perhaps there is something that causes these bundlers to fail that I'm unaware of. Of course, I'm happy to fix once I understand what might be causing this. If you can provide further information, I'd much appreciate it 🙏

**Comment by Jaywaa** [comment]
It just seems to break with the snowpack dev server (and skypack.dev). It works on my production environment so assume it has something to do with how they handle package caching / module reloading. Closing this issue because it seems like more of a "them" issue. Thanks for the awesome package @nvie.

**Comment by nvie** [comment]
Thx for taking the time to report a potential bug!
