### ISSUE TITLE
WeakGuard in 2.x

### ISSUE THREAD

**Issue by sfarthin** [nvie/decoders#813]
**Please confirm:**
- [x] I have read the [migration instructions](https://github.com/nvie/decoders/blob/main/MIGRATING-v2.md)

**What is the problem?**
- [ ] I found a bug in the migration instructions
- [x] I ran into an issue that the migration instructions don't give clear guidance on
- [ ] Something else

**Description**
We use something like `WeakGuard` as the default. Is there some built-in mechanism that doesn't involve wrapping verify in a try/catch ?

[See related issue](https://github.com/nvie/decoders/issues/521#issue-643911158).

```typescript
// Paste your v1.x code here
```

**Comment by nvie** [comment]
Hmm. Good point! I forgot about that issue, but re-reading the linked issue, I'd still like to provide that `onError` API. You can implement it manually for now as:

```ts
function weakGuard<T>(decoder: Decoder<T>): (blob: unknown) => T {
  return (blob: unknown) => {
    const result = decoder.decode(blob);
    if (result.ok) {
      return result.value;
    } else {
      return onError(formatInline(result.error), blob);  // May or may not throw
    }
  };
}
```

But I agree, this would be a nice addition to the API by default. Let me think about it for a bit more to see how we can make this a nice and stable API—I will get back to you on this soon!

**Comment by tdreyno** [comment]
I had been wrapping `verify` in a Result for this approach. Its a well understood pattern, the Result type is already in the library.

**Comment by nvie** [comment]
@tdreyno Instead of wrapping `.verify()` in a `Result`, you can use the `.decode()` method instead, which does the same thing. See slso https://decoders.cc/#using-a-decoder. (Technically, `.verify()` is a wrapper around `.decode()` of itself already, so that would be double-wrapping things to get the same Result values.)
