### ISSUE TITLE
Migration help needed: .map to .transform

### ISSUE THREAD

**Issue by asmaloney** [nvie/decoders#822]
**Please confirm:**
- [x] I have read the [migration instructions](https://github.com/nvie/decoders/blob/main/MIGRATING-v2.md)

**What is the problem?**
- [ ] I found a bug in the migration instructions
- [ ] I ran into an issue that the migration instructions don't give clear guidance on
- [x] Something else

**Description**
I had a `map` which was converting a string to a [luxon](https://github.com/moment/luxon/) DateTime.

```typescript
import { Decoder, map, string } from 'decoders'
import { DateTime } from 'luxon'
export const transformDateTime: Decoder<DateTime> = map(string, (isoDate) => {
    const dt = DateTime.fromISO(isoDate)
    if (dt.invalidExplanation) {
      throw `Unable to parse date ${isoDate}: ${dt.invalidExplanation}`
    }
    return dt
  }
)
```

I use this whenever I use DateTime - e.g.:
```typescript
const decodeFoo = object({
  id: string,
  expires: transformDateTime,
})
```

I migrated it like this (simple!):
```typescript
import { Decoder, string } from 'decoders'
import { DateTime } from 'luxon'
export const transformDateTime: Decoder<DateTime> = string.transform(
  (isoDate) => {
    const dt = DateTime.fromISO(isoDate)
    if (dt.invalidExplanation) {
      throw `Unable to parse date ${isoDate}: ${dt.invalidExplanation}`
    }
    return dt
  }
)
```

Now my page fails to load with an error:
```
Uncaught TypeError: string.transform is not a function
```

 I've looked at the generated code of the private package and it still looks correct to me. I get this (the .d.ts):
```typescript
import { Decoder } from 'decoders';
import { DateTime } from 'luxon';
export declare const transformDateTime: Decoder<DateTime>;
```

and this (the .js):
```js
import { string } from 'decoders';
import { DateTime } from 'luxon';
export const transformDateTime = string.transform((isoDate) => {
    const dt = DateTime.fromISO(isoDate);
    if (dt.invalidExplanation) {
        throw `Unable to parse date ${isoDate}: ${dt.invalidExplanation}`;
    }
    return dt;
});
```

Possibly useful extra info:
- this is in a private package which I include in my app
- `transformDateTime` is only used internally in the private package (none of the decoders are exported from the package)
- it's quite possible I'm misunderstanding something -  I'm a C++ guy, not a JS/TS expert :-)

Any suggestions? Thank you!

**Comment by nvie** [comment]
> _”Now my page fails to load with an error:”_
> ```Uncaught TypeError: string.transform is not a function```

This error almost looks like you’re still importing from v1 of decoders. Is there any chance you haven’t actually upgraded the `decoders` version in your `node_modules` to v2.0.0?

The migrated code you pasted here all looks solid to me!

**Comment by asmaloney** [comment]
I think maybe something was being cached somewhere... I shutdown vite, removed node_modules & package-lock.json in both the private package and the app, reinstalled & relinked everything, and started up again and... it magically worked.

Thanks for the quick response (and the package)!

**Comment by nvie** [comment]
Great! Hope everything else works as expected for you! If not, let me know 🙏
