### ISSUE TITLE
Package requires nodejs 10 or newer, but this is not documented.

### ISSUE THREAD

**Issue by Wizarth** [nvie/decoders#884]
**Description of the bug**
The global URL was introduced in NodeJS in version 10, and is referred to in the url decoder.
Trying to use this package on an earlier version of NodeJS (e.g. 8.17.0) results in an error when importing the module.

**Expected behavior**
I expect NPM to prevent me from installing (version 2?) of this package, due to having `{engines: { node: '>=10'}}` in package.json

**To Reproduce**
index.js
``` javascript
require('decoders');
```
Command line:
``` bash
node index.js
```

**Additional context**
Decoders version: 2.0.1
TypeScript version: 4.5.5
Node version: 8.17.0

I know Node10 is a relatively ancient version, so its reasonable to expect its features to exist, but it would be really appreciated if the minimum expected engine version was specified, ideally in both the README/documentation and in the package.json .

**Comment by Wizarth** [comment]
Just to add to this - I was able to work around this by importing `core-js/proposals/url` before importing `decoders`.

**Comment by nvie** [comment]
Thanks for reporting this! I've updated the docs to mention this now (see 015aa155ccb1). Decided not to enforce it through an `engines` config, as you can still use it if you manually include the polyfill.
