### ISSUE TITLE
URL decoder does not accept URLs with / in the query part

### ISSUE THREAD

**Issue by gcampax** [nvie/decoders#979]
**Description of the bug**
As subject says, `D.url` will reject URLs that have forward slashes in the query part.

**Expected behavior**
Those URLs are valid and should be accepted. See https://datatracker.ietf.org/doc/html/rfc3986#section-3.4 where / is explicitly called out as a valid character in query.

**To Reproduce**
```
const D = require('decoders')
D.url.verify("https://example.com/foo?q=foo/bar")
```

**Additional context**
Decoders version: 2.0.3
TypeScript version: 5.1.3
Node version: 18.14.2

**Comment by nvie** [comment]
Published the fix in 2.0.4 — thanks for flagging the issue, @gcampax 🙏 !
